# Site settings
title: Jeremy Cohen
email: jmcohen [at] princeton [dot]
description: > # Personal Blog of Jeremy Cohen
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://jmcohen.github.io" # the base hostname & protocol for your site
github_username:  jmcohen

# Build settings
markdown: kramdown
